export const SAVE_USERDATA = 'SAVE_USERDATA';
export const REMOVE_USERDATA = 'REMOVE_USERDATA';
export const UPDATE_USER_ONESIGNALID = 'UPDATE_USER_ONESIGNALID';

export const FETCH_LOGIN_DATA = 'FETCH_LOGIN_DATA';
export const GET_LOGIN_DATA = 'GET_LOGIN_DATA';
export const LOGOUT = 'LOGOUT';

export const FETCH_REGISTER_DATA = 'FETCH_REGISTER_DATA';
export const GET_REGISTER_DATA = 'GET_REGISTER_DATA';


export const FETCH_PRODUCT_RECOMMENDATION = 'FETCH_PRODUCT_RECOMMENDATION';
export const GET_PRODUCT_RECOMMENDATION = 'GET_PRODUCT_RECOMMENDATION';

export const FETCH_RECOMMENDATION_REMINDER = 'FETCH_RECOMMENDATION_REMINDER';
export const GET_RECOMMENDATION_REMINDER = 'GET_RECOMMENDATION_REMINDER';
export const RESET_REMINDER = 'RESET_REMINDER';

export const FETCH_BUY_REQUEST = 'FETCH_BUY_REQUEST';
export const SEND_BUY_REQUEST = 'SEND_BUY_REQUEST';
export const UPDATE_BUY_REQUEST = 'UPDATE_BUY_REQUEST';


export const FETCH_CART = 'FETCH_CART';
export const GET_CART = 'GET_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_CART = 'DELETE_CART';


export const FETCH_DEMAND_DATA = 'FETCH_DEMAND_DATA';
export const GET_DEMAND_DATA = 'GET_DEMAND_DATA';
export const SUBSCRIBE_DEMAND = 'SUBSCRIBE_DEMAND';

export const FETCH_ANALYTICS_DATA = 'FETCH_ANALYTICS_DATA';
export const GET_ANALYTICS_DATA = 'GET_ANALYTICS_DATA';
export const DELETE_ANALYTICS_SUBSCRIBE = 'DELETE_ANALYTICS_SUBSCRIBE';


export const FETCH_REQUEST_DATA = 'FETCH_REQUEST_DATA';
export const GET_REQUEST_DATA = 'GET_REQUEST_DATA';
export const DELETE_REQUEST_DATA = 'DELETE_REQUEST_DATA';


export const FETCH_NOTIFICATION_DATA = 'FETCH_NOTIFICATION_DATA';
export const GET_NOTIFICATION_DATA = 'GET_NOTIFICATION_DATA';
