export const SAVE_USERDATA = 'SAVE_USERDATA'
export const REMOVE_USERDATA = 'REMOVE_USERDATA'


export const FETCH_LOGIN_DATA = 'FETCH_LOGIN_DATA'
export const GET_LOGIN_DATA = 'GET_LOGIN_DATA'
export const LOGOUT = 'LOGOUT'


export const FETCH_REGISTER_DATA = 'FETCH_REGISTER_DATA'
export const GET_REGISTER_DATA = 'GET_REGISTER_DATA'


export const FETCH_PRODUCT_RECOMMENDATION = 'FETCH_PRODUCT_RECOMMENDATION'
export const GET_PRODUCT_RECOMMENDATION = 'GET_PRODUCT_RECOMMENDATION'
